### ISSUE TITLE
maxiconda.sh missing

### ISSUE THREAD

**Issue by nerohmot** [Semi-ATE/maxiconda#34]
release fails with :

![image](https://user-images.githubusercontent.com/3516972/205679716-477bee72-56e2-4bc0-bc06-691abe903d7a.png)

seems the maxiconda.sh file is not uploaded to the release assets ...

**Comment by nerohmot** [comment]
@andfoy the consolidation of the release didn't pass, I think the maxiconda.sh file is not present to uploaded to the release assets.
Can you have a look at it ?

**Comment by andfoy** [comment]
We forgot to update the upload step as well, as the file now has the version number on it

**Comment by nerohmot** [comment]
hang on ... the `maxiconda.sh` can not have the release number added to the name, because the link on `www.maxiconda.org` is `https://github.com/Semi-ATE/maxiconda/releases/latest/download/maxiconda.sh` ! 
see the conversation on Slack (with Staphannie) :
![image](https://user-images.githubusercontent.com/3516972/205690310-327aaeb7-d745-4cec-b589-6b55e62938c1.png)
